manytask/manytask

manytask/api.py, manytask/course.py, manytask/gdoc.py, manytask/static/style.css, manytask/templates/base.html, manytask/templates/layout.html, manytask/templates/reviews.html, manytask/templates/tasks.html, manytask/web.py
Add separate page with task reviews scores input 
Add histogram images on hover at the tasks page
=> feat: Add task review by students

manytask/api.py, manytask/deadlines.py, manytask/gdoc.py, manytask/main.py, manytask/static/style.css, manytask/templates/base.html, manytask/templates/tasks.html, manytask/web.py
Create front and api for bonus score for tasks with low demand
=> feat: Low demand bonus

.github/workflows/pr-title.yml
Closes #52
Add github workflow to run each PR.
Just to maintain Pull Request titles to use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).
General
Added tests?
Added to documentation?
=> ci: check PR title

.github/dependabot.yml
=> ci: add dependabot updates configuration

manytask/glab.py
Related to 
* #
* #
* 
Closes #
=> feat: add ci_config_path from public repo (.gitlab-ci.yml@path/to/repo)

.github/workflows/test.yml, Dockerfile, manytask/gdoc.py, manytask/web.py
Related to 
* #
* #
* 
Closes #
=> feat: try to use alpine docker

.github/workflows/test.yml
ruff now requires 'check' keyword, which was not added to the yml Actions config. Broken (presumably) in d4b12ea220f338bc2081a5f04a910fdd8fa16b12
Related to 
* #
* #
* 
Closes #
=> fix: Fix ruff script in linter

manytask/gdoc.py
After dependencies were updated, some of the function calls were marked as type-unsafe by mypy. This change fixes the problem by explicitly assigning types to the variables where needed.
=> fix: mypy errors

tests/.manytask.test.yml
Related to 
* #
* #
* 
Closes #
=> fix: change the date format in the samle yml file

.github/workflows/test.yml, Dockerfile, docker-compose.production.yml
The python package was updated by dependabot, but previous version of python was still requested in several places. This change fixes the issue, finalizing the update to 3.13
=> fix: update python to 3.13

manytask/models.py, requirements.txt, tests/test_models.py
Create flask sqlalchemy orm models in models.py.
Add simple tests for models in tests/test_models.py.
Add necessary modules to requirements.txt.
[Database scheme](https://drawsql.app/teams/gagarinkomar/diagrams/copy-of-manytask-2)
=> feat: add db models for DatabaseApi

.env.example, .gitignore, manytask/database.py, manytask/main.py, tests/.deadlines.test.yml, tests/.deadlines.test2.yml, tests/test_db_api.py
Created DataBaseApi class derived from abstract StorageApi.
Created get_or_create, update_or_create, etc. methods like django funcs.
Add tests to this class(tests/test_db_api.py).
=> feat: create database api class

docker-compose.production.yml
- Updated environment variables for the manytask service to reflect the new virtual host and letsencrypt settings.
- Updated volume mounts for the acme-companion service to include read-write permissions for certs, vhost, and html.
=> chore: update docker-compose configuration for production environment

.env.example, manytask/database.py, manytask/main.py, tests/test_db_api.py
Added CREATE_TABLES_IF_NOT_EXIST flag in env.
If flag is True and tables don't exist, in DataBaseApi tables will be created.
Added test for it.
=> feat: add auto creation of tables in database

README.md, docs/deadline_schedule.md
=> docs: Deadline checklist

tests/test_models.py
Need to bump coverage
Closes #219
=> test: Full coverage models.py

tests/test_glab.py
Cover the interaction with Gitlab by tests
[#215](https://github.com/manytask/manytask/issues/215)
Now coverage:
manytask/glab.py               94%
=> feat: Cover the interaction with Gitlab by tests #215

.github/workflows/test.yml
With more branches in the repo it is convenient to trigger tests on all PRs, not only when targeting main branch and also when changes are pushed to any branch
=> feat: Run tests on all pull request and when changes are pushed to any branch

manytask/database_utils.py, manytask/templates/database.html, tests/test_database_utils.py, tests/test_web.py
In many case it is important to match students with their names (e.g. when we don't know the name <-> nickname relation). This may be temporary solution, but it is needed currently.
Issue #346
=> feat: Show student names in the scores table and CSV export (#366)

manytask/course.py
Access the new fields via decorated getters.
This is a follow-up for #354
=> refactor: Make fields added to the Course object private

manytask/abstract.py, manytask/database.py, manytask/main.py, tests/test_database.py, tests/test_db_api.py
=> refactor: remove redundant methods split in Storage API

manytask/database.py
I'm not sure, but are there any situations where this is needed now?
=> feat: remove unnecessary session refreshes

.github/workflows/docs.yml
Update NodeJS to version 20.18.1
=> fix: Fix github pages

.github/workflows/test.yml
When we are pushing into open PR, 2 actions are triggered on it. This fix it.
=> ci: correct using 'on'

manytask/database.py, tests/conftest.py, tests/test_db_api.py
Now, `Session` for DB tests are being created for each test. Also in this tests inside `DataBaseApi` one more session was being created.
I extended `DataBaseApi` and now we can use one session in tests
=> fix: data leak in `test_data_api.py`

.env.example, docs/dev.md
This add docs how to get started dev (based on my experience)
https://docs-test.manytask2.org/
=> docs: add docs how to get started dev

.manytask.example.yml, docs/grading.md, docs/toc.yaml
=> docs: add docs and examples on configuring final grade

manytask/templates/create_course.html
=> fix: default names for public repo and students groups

.github/workflows/deploy.yaml
=> fix: revert bump appleboy/ssh-action

manytask/auth.py, manytask/database.py, manytask/utils.py, manytask/web.py
If the user was originally registered on gitlab, corresponding entity is not created in manytask upon login. This also means, I can't transfer admin rights to other user before creating a new course
=> fix: Automatically create user on login

manytask/database.py, manytask/models.py, manytask/templates/layout.html, tests/test_models.py
This add optimization to course page. Now page will be load ~0.2-0.3 seconds less
On test.manytask2.org:
=> perf: optimization of the course page rendering

manytask/glab.py, tests/test_glab.py
=> refactor: optimize repo existance check

manytask/templates/layout.html
=> fix: Don't account for bonuses in the score display
