manytask/manytask

manytask/gdoc.py

If a username consists of only digits, it is returned as a number by gspread.Worksheet.col_values

fix: cast found_login to str when searching for existing rows

---

Dockerfile

It's convenient to use for docker health checks

chore(docker): Add curl to docker image

---

manytask/templates/base.html

Remove x-scroll appearing in some browsers
Before commit:
After:

fix: remove x-scroll

---

manytask/api.py

Current version of a checker returns score as a string that represents float number, which is casted directly to int. This cause a value error.
The proposed fis allow to push integers or floats in the score string, with the following behavior:
1. If integer is passed, it is taken as final score for the task
2. If a float less than zero is passed, set the score to 0
3. If a float larger than 2.0 is passed, report and error
4. If a float between 0.0 and 2.0 is passed, use it a fractional score, i.e. multiply it by the maximum score for the task.

fix: Allow non-integer number format for score reporting

---

manytask/templates/signup.html
manytask/web.py

Currently, Manytask registration form asks to type password only once. Usually, when user is asked to set the password, it is typed twice. This is done to prevent setting password with a typo in it. Users are so used to having two forms when setting the password, they get confused whe asked to do it once, thinking that they need to type password that they set previously. This commit (1) adds another textfield to re-type password and (2) checks if two typed passwords are the same.

feat: ask to re-type password

---

docs/production.md

After 0.9 release, the course is configured by one file instead of two. This information was not fully propagated to the documentation. This fixes docs on how to use curl with the new style of configs.

documentation: Minor update to the documentation

---

manytask/abstract.py
manytask/api.py
manytask/course.py
manytask/gdoc.py
manytask/main.py
manytask/web.py

Separate GoogleDocApi into GoogleDocViewerApi and GoogleDocStorageApi.
Separate RatingTable into ViewerRatingTable and StorageRatingTable.
In Course instead of googledoc_api using viewer_api and storage_api.
Create abstract classes(ViewStoreApi, RatingApiBase, ViewerRatingApi, StorageRatingApi).
ViewStoreApi using in initial classes like GoogleDocViewerApi/GoogleDocStorageApi for having fetch_rating_api method.
RatingApiBase using in viewer/storage classes like ViewerRatingTable/StorageRatingTable for having methods which work with cache.
ViewerRatingApi/StorageRatingApi also unsing in viewer/storage classes for having view/store data methods.

refactor: separate and make abstract gdoc api

---

manytask/abstract.py
manytask/api.py
manytask/course.py
manytask/gdoc.py
manytask/main.py
manytask/models.py
manytask/web.py
requirements.txt
tests/test_models.py

Although it is very convenient to use google spreadsheets as a database, there are certain limitations that come with it. First ad formost, the google sheet does not allow to make several courses on a single web-application instance. Secondly, this solution relies on google api and service accounts, which may become unavailable. This change is the first step to make it possible to use database. It makes all the data interfaces abstract, which allows to switch between two backends. Also this change contains the design of the database, which can be in future used to store the data on many courses. This change, however, keeps the one-web-application - one-course paradigm to keep backward compatibility and allow comparison testing.

feat: create a database and make it possible to use it instead of gsheet

---

.env.example
manytask/main.py

Edited main.py. Added variables to .env.example.
If USE_DATABASE_AS_STORAGE=true app using DataBaseApi instead of GoogleDocApi as storage_api.
fix: add SHOW_ALLSCORES to .env.example
This param added before in main branch, it using in manytask/local_config.py:LocalConfig.

refactor: add database supporting

---

.env.example
.gitignore
manytask/database.py
manytask/main.py
manytask/models.py
tests/.deadlines.test.yml
tests/.deadlines.test2.yml
tests/test_db_api.py
tests/test_models.py

Changed lazy='dynamic' to DynamicMapped, it is the same thing but more convenient.
In Grade instead of User relationship using UserOnCourse.
Swapped TaskGroup and Task for convenience(link to course now in TaskGroup instead of Task).
Removed unused fields: is_manytask_admin, is_course_admin.
Add gitlab_instance_host field to course and validation gitlab_instance_host equal when creating UserOnCourse.
Also edited test_models.py
Current scheme:
https://drawsql.app/teams/gagarinkomar/diagrams/copy-of-copy-of-manytask

refactor: edit models

---

manytask/web.py
requirements.txt

In web.py, most of the requests handle authorization with their own logic. They should use @requires_auth
@requires_ready decorators instead.
Closes https://github.com/manytask/manytask/issues/232

refactor: @requires_ready and @requires_auth in web requests

---

manytask/abstract.py
manytask/database.py
manytask/gdoc.py
manytask/models.py
manytask/web.py
tests/test_abstract.py
tests/test_db_api.py
tests/test_gdoc.py
tests/test_models.py
tests/test_web.py

Added is_course_admin field for UserOnCourse model.
Added get_stored_user(get user data from storage) and sync_stored_user(sync user data to storage) methods to abstract StorageApi class.
Edited web views to support stored user data. Now user is considered an admin when he admin in gitlab or manytask.
In login_finish view syncing course_admin flag from gitlab to storage.
Added tests for models, views and DB api.

feat: add synchronization course_admin from gitlab to manytask

---

manytask/auth.py
manytask/web.py
tests/test_web.py

Fix requiring secret word for each course
[#237](https://github.com/manytask/manytask/issues/237)
future tasks:
- accord check to db user->course record
- extract secret check from signup and create_project handlers to decorator
- develop more clean logic for signup and logic flow 
**Login button flow**
1. if you don't have fork
- ask secret
- create fork
- redirect on main
2. you have already got fork
- check if you have fork
- redirect on main

feat: secret check

---

manytask/models.py

With this change, indexes, unique constraints, check constraints, foreign keys, and primary keys will be automatically named following a consistent pattern.
For example, if we add new field like this:
```
new_field: Mapped[str] = mapped_column(unique=True, nullable=True)
```
Alembic create migration:
```
def upgrade() -> None:
op.add_column('some_model', sa.Column('new_field', sa.String(), nullable=True))
op.create_unique_constraint(None, 'some_model', ['token'])
def downgrade() -> None:
op.drop_constraint(None, 'some_model', type_='unique')
op.drop_column('some_model', 'new_field')
```
In this case, there is a problem without manually changing migrations. If we call downgrade after migration we get an error:
```
sqlalchemy.exc.CompileError: Can't emit DROP CONSTRAINT for constraint …
```

fix: add naming convention for database

---

Dockerfile

Docker was complaining about using different registry for keywords

fix: Supress Docker build warning

---

manytask/database_utils.py

If user deletes an account from gitlab, their data remains in Manytask. But when we request their name via GitLab API, exception is thrown. In this change the exception is caught and empty name is assigned to the user.

fix: Catch exception when user is deleted from gitlab

---

.github/workflows/test.yml

Somehow when loaded from cache the venv appears broken. This disables caching to fix the problem.

fix: Disable poetry cache

---

manytask/abstract.py
manytask/api.py
manytask/auth.py
manytask/course.py
manytask/database.py
manytask/database_utils.py
manytask/glab.py
manytask/main.py
manytask/web.py
tests/conftest.py
tests/test_api.py
tests/test_auth.py
tests/test_database_utils.py
tests/test_db_api.py
tests/test_glab.py
tests/test_main.py
tests/test_web.py

Added course_name for url paths. Used course_name of url instead of app.course_name.
Edited login path: requires_auth only checks login, requires_ready only checks course ready, requires_course_access checks previous two and user participation in the course.
Removed course_admin and repo from session.
Edited tests.

feat: pass course name in url and edit auth path

---

.manytask.example.yml
manytask/abstract.py
manytask/api.py
manytask/auth.py
manytask/config.py
manytask/database.py
manytask/database_utils.py
manytask/main.py
manytask/templates/database.html
manytask/templates/layout.html
manytask/templates/not_ready.html
manytask/templates/signup.html
manytask/templates/tasks.html
manytask/web.py
tests/test_api.py
tests/test_database.py
tests/test_database_utils.py
tests/test_db_api.py
tests/test_web.py

Removed storing course_name from DataBaseApi. Instead, passing course_name as a methods parameter. This removes the link to a single course and makes it possible to use multiple courses through one DataBaseApi.
Also removed course fields from DataBaseApi like registratin_secret etc...
Added method for course creation. It initializes the course and after that you can upload a config with deadlines to this course. We are currently initializing the course at startup, but in the future it will be easy to transfer the creation to the form.
Edited tests.
These are the final changes before moving to many courses

feat: remove link to the course in DataBaseApi

---

.env.example
manytask/abstract.py
manytask/auth.py
manytask/database.py
manytask/glab.py
manytask/local_config.py
manytask/main.py
manytask/templates/courses.html
manytask/templates/create_course.html
manytask/templates/layout.html
manytask/templates/signup.html
manytask/utils.py
manytask/web.py
tests/conftest.py
tests/test_api.py
tests/test_auth.py
tests/test_database.py
tests/test_database_utils.py
tests/test_main.py
tests/test_web.py

Removed course_name from app object. Also removed extra course params from .env.
Added supporting many courses.
Added admin endpoint with creating course.
Added list of courses to main page.
Slightly changed the authentication logic. Added state while gitlab login. This allows you to return to the same page where you was.
Edited tests.

feat: add supporting many courses

---

manytask/database_utils.py
manytask/templates/database.html
tests/test_database_utils.py

Now, the DB looks like this:
```Name``` is replaced by two columns: ```First Name``` and ```Last Name```. Search is working on any column.
And some UI updates (you can see this on screenshot), to my mind now it looks better, but I'm ready to listen criticism

feat: add first and last name in score table

---

manytask/abstract.py
manytask/database.py
manytask/database_utils.py
manytask/templates/database.html
tests/test_database_utils.py
tests/test_db_api.py
tests/test_web.py

This PR improve speed of rendering table at twice. Even visually I can see strong difference.
Some benchmark tests (if I wrote their correctly :) ):
```test_db (NOW)``` - **old** realisation
```test_db (0004_...)``` - **new** realisation
When we have ```1000``` users on course:
When we have ```500``` users:
When we have ```100``` users:
But I had to change a signature of method ```get_all_scores```, now it is ```get_all_scores_with_names```. In this method I make new ```dict``` for names, where key is ```username```, but we already have ```dict``` with key ```username```(```all_scores```). And maybe will be good if we combine them, but in my case tests is refactoring very quickly and code is readable

perf: optimize calls to db when table is rendering

---

manytask/abstract.py
manytask/auth.py
manytask/glab.py
tests/test_api.py
tests/test_auth.py
tests/test_glab.py
tests/test_web.py

The username is used to construct path to a project, hence it should be provided directly, not inside a container.

refactor: Use username instead of Student when checking if the project exists

---

Dockerfile
manytask/main.py

Now we can see ```access``` and ```error``` logs in docker console and in ```access.log```, ```general.log```, ```error.log``` files.
And very minor change format logs for readability improvements

fix: application logs are't displayed

---

manytask/web.py

We check if the user is instance admin and re-seting the admin-on-course when checking course access.
Note that now user can not become course admin by providing course token instead of a secret. This status should be set elsewhere.

refactor: Do not set admin status when projects are created

---

manytask/abstract.py
manytask/auth.py
manytask/glab.py
tests/test_api.py
tests/test_auth.py
tests/test_web.py

If we get a 401 error when trying to verify if the user is logged in, we try to update the token.

feat: refresh oauth token

---

.github/workflows/deploy.yaml

Docker caches layers very strangely and the documentation is not updated without this flag.

fix: fix problem with docker cache

---

manytask/database.py
manytask/database_utils.py
manytask/static/css/layout.css
manytask/templates/database.html
manytask/web.py
tests/constants.py
tests/test_database_utils.py

Resolves #552 #551 
If current percent is zero without reload page impossible to calculate new percent, else percent recomputing correct.

fix: round percents to decimals and computing percent without reload
